/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Imebra
 #	author : miyako
 #	2016/12/06
 #
 # --------------------------------------------------------------------------------*/

#include <imebra/imebra.h>
#include <list>

#include "libpng16/png.h"
#include "libjson/libjson.h"

#define INCHES_PER_METER (100.0/2.54)

// --- Imebra
void Imebra_Get_images(sLONG_PTR *pResult, PackagePtr pParams);
void write_data_fn(png_structp png_ptr, png_bytep buf, png_size_t size);
void output_flush_fn(png_structp png_ptr);